[build-system]
requires = ["setuptools_scm@git+https://github.com/Chia-Network/setuptools_scm.git@master#egg=setuptools_scm", "setuptools>=42", "wheel", "setuptools_scm[toml]>=3.5.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
local_scheme = "no-local-version"
